name: Deploy UrbanCart Website

on:
  push:
    branches:
      - test

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages-test
  cancel-in-progress: true

jobs:
  deploy-test:
    environment:
      name: test
      url: https://dandemutande.github.io/urbancart-test/

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Prepare test build
        run: |
          mkdir public
          cp -r Website/* public/

      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: public

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
